### ISSUE TITLE
dist/index.js does not exist after npm install

### ISSUE THREAD

**Issue by colbygk** [imrvelj/moment-random#1]
How to reproduce:
```
$ npm install moment-random

+ moment-random@1.0.2
added 1 package in 2.56s
$ node -e "require ('moment-random')"
module.js:471
    throw err;
    ^

Error: Cannot find module 'moment-random'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.runInThisContext (vm.js:97:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at evalScript (bootstrap_node.js:353:27)
```

This appears to be due to a missing `dist/index.js` in `./node_modules/moment-random/` after the npm install. It also appears that the contents of `src/` are also missing after the npm install.

System configuration:
  - OS: Ubuntu 14.04.4 LTS
  - Node: v6.11.3
  - NPM: 5.4.2

**Comment by perpaer** [comment]
Hey, thanks for reporting!
I'll look into it ASAP.

**Comment by perpaer** [comment]
Fixed in new version. (1.0.3)
Thanks again!
